# A service is Docker's way of saying: "A container that is part of this application."
services:
  backend: # This is the name of the service. It can be anything you want.
    build: # This tells Docker to build an image for this service.
      context: ../.. # Build context. Docker can only access files inside this directory. "../.." moves from docker/development back to the project root (server/).
      dockerfile: docker/development/Dockerfile # This tells Docker which Dockerfile to use for building the image.
    container_name: backend-dev # This is the name of the container that will be created from the image. It can be anything you want, if not specified docker will genearte one random.
    restart: unless-stopped # This tells Docker to restart the container if it stops, unless it was stopped manually.
    # working_dir: /app # This is the working directory inside the container. I commented because i added it in Dockerfile so.
    ports:
      - "5000:5000" # This tells Docker to map port 5000 on the host to port 5000 on the container. This is how you can access the backend from your host machine.
    env_file:
      - .env # This tells Docker to use the .env file to set environment variables.
    environment:
      NODE_ENV: development # This sets the NODE_ENV environment variable to "development".
      CHOKIDAR_USEPOLLING: "true" # This sets the CHOKIDAR_USEPOLLING environment variable to "true". This is required for hot reloading to track the changes.

    volumes:
      - ../../:/app # Everytime we make changes in code locally we need to stop container, then buld and run again and again. to avoid this we use volumes bind mount. Bind mount ===>>> Whatever exists on Windows immediately appears inside Linux. This is called a Bind Mount.
      # Nodemon sees the change. Server restarts. No rebuild. This is why hot reload works.
      - node_modules:/app/node_modules # If we don't do this, in container node_modules generated by linux is overridden by windows generated node_modules or empty or no node_modules at all so we get error.
      # volumes:
      #   - node_modules:/app/node_modules --- means: "Use a volume named node_modules."
      #   - "/app/node_modules" means: "Mount it from the host machine at the path /app/node_modules."

      # Why don't we mount "uploads" separately? Right now: "uploads/" is already inside: "../../:/app" So uploads are available automatically.
      # In production, we'll mount uploads as a dedicated volume because uploaded files must survive container replacements independently of the source code.
    depends_on: # This tells Docker to wait for the MongoDB container to start before starting the backend container. It only controls container start order.
      mongodb: # Wait for the mongodb service.
        condition: service_healthy # Wait until its healthcheck passes.

  mongodb:
    image: mongo:7 # This is the Docker image to use for the MongoDB container.
    container_name: mongodb # This is the name of the container that will be created from the image. It can be anything you want, if not specified docker will genearte one random.
    restart: unless-stopped # This tells Docker to restart the container if it stops, unless it was stopped manually.
    ports:
      - "27017:27017" # This tells Docker to map port 27017 on the host to port 27017 on the container. This is how we can access the MongoDB from our host machine.
    volumes:
      - mongo-data:/data/db # This tells Docker to use a volume named mongodb_data for the MongoDB data directory. This is how we persist data across container restarts.

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
# ===============================================
# Named Volumes
# ===============================================
volumes:
  node_modules: # means:"Create a Docker-managed volume named node_modules if it doesn't already exist."
  mongo-data: # means:"Create a Docker-managed volume named mongodb_data if it doesn't already exist."
