# ==========================================================
# Main Nginx Configuration
# ==========================================================

user nginx;
# Runs Nginx workers as the nginx user instead of root where possible.

worker_processes auto;
# Nginx automatically determines an appropriate number of worker processes based on available CPU cores.

# error_log /var/log/nginx/error.log warn;
# Nginx error log.

pid /var/run/nginx.pid;


events {
    worker_connections 1024;
}
# Controls how many connections each worker can handle.


http {
# Everything related to HTTP traffic goes inside this block.
    include /etc/nginx/mime.types;

    default_type application/octet-stream;

    # ------------------------------------------------------
    # Logging
    # ------------------------------------------------------
    # Defines the format of Nginx access logs.
    log_format main
        '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent"';

    # access_log /var/log/nginx/access.log main;
    # records requests such as:GET /health, POST /api/auth/login, GET /api/users
    # This is separate from our Node.js application logging.
    access_log /dev/stdout main;

    error_log /dev/stderr warn;

    # ------------------------------------------------------
    # Performance
    # ------------------------------------------------------

    sendfile on;
    # Enables efficient file transmission.

    keepalive_timeout 65;
    # Keeps HTTP connections alive for a period of time rather than immediately closing them.

    # ------------------------------------------------------
    # Request Limit
    # ------------------------------------------------------
    client_max_body_size 20M;
    # Nginx rejects requests larger than 20 MB before they reach Node.js. That's useful because our backend supports file uploads.

    # ------------------------------------------------------
    # Security
    # ------------------------------------------------------

    server_tokens off;
    # Prevents Nginx from unnecessarily exposing its version in responses.

    add_header X-Content-Type-Options "nosniff" always;
    # Prevents browsers from trying to guess a different content type.

    add_header X-Frame-Options "SAMEORIGIN" always;
    # Restricts our pages from being embedded by another origin in a frame.

    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    # Controls how much referrer information browsers send to other origins.

    # ------------------------------------------------------
    # Load Server Configurations
    # ------------------------------------------------------

    include /etc/nginx/conf.d/*.conf;
    # This is important for your finalized folder structure. Our actual reverse-proxy configuration will live in: docker/production/nginx/conf.d/
}